GET https://doorctl-dev/api/users

###

GET https://doorctl-dev/api/users/1

###

POST https://doorctl-dev/api/users

{
    "name": "First Last",
    "pin": "0000",
    "card": 23456,
    "facility": 789
}

###

PUT https://doorctl-dev/api/users/2

{
    "name": "First Last",
    "pin": "0000",
    "card": 23456,
    "facility": 789
}

###

DELETE https://doorctl-dev/api/users/2
